image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar artifacts/aqa-shop.jar -P:profile=test
  - java -Dspring.datasource.url=jdbc:postgresql://localhost:5432/app -jar artifacts/aqa-shop.jar -P:profile=test&
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true
  - ./gradlew clean test -Ddb.url=jdbc:mysql://localhost:3306/app
  - ./gradlew clean test -Ddb.url=jdbc:postgresql://localhost:5432/app