image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off
install:
  - step:
    name: Start MySQL Container
    image: mysql:8.0.18
    script:
      - docker run --name mysql-container -p 3306:3306 -e MYSQL_ROOT_PASSWORD=pass -d mysql:8.0.18
      - sleep 60
      - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar artifacts/aqa-shop.jar -Pprofile=test&
      - chmod +x gradlew


build_script:
  - ./gradlew test --info -Dselenide.headless=true
  - ./gradlew clean test -Ddb.url=jdbc:mysql://localhost:3306/app
